### ISSUE TITLE
Notes/issues from an install

### ISSUE THREAD

**Issue by mhulse** [registerguard/ap_wfm#8]
# TODO:
- [x] ~~Figure out why the `logs/` folder wasn't getting created on Rob's computer.~~
  - Logs folder wasn't working because the script wasn't working.
- [x] ~~Create an example `ap_wfm_settings.py` and document that folks need this file.~~
  - Just put `settings.py` and `urls.py` info in `README.md`.
- [x] ~~Should we include a "stub" django project to make this easier on future users?~~
  - See note above. People can setup their own Djanog 1.3.1 virtual env for testing locally.
- [ ] ~~Need to figure `ballot/templatetags/humanize_list.py` mess (is this `pip` installable anywhere?)~~
  - We think it will work to put `humanize_list.py` inside the app. John says Django will find the first version of that code and stop ('cause we probably have it installed elsewhere on projects.rg.com).
- [ ] Update readme with installation instructions (could use some clean up):
# Notes:

Tested against Django `1.3.1`.
### Clone [ap_wfm](https://github.com/registerguard/ap_wfm):

This repo contains the AP "Web Feeds Manager" special sauce.
### Make virtual env:

``` bash
$ mkvirtualenv django_root
```

… and work on it:

``` bash
$ workon django_root
```
### Pip install a Django

``` bash
$ pip install django==1.3.1
```
### Create a project:

``` bash
$ django-admin.py startproject mysite
```
### Add app to settings:

… installed apps, add `ap_wfm` and uncomment the docs.
### Create symbolic link:

… to the `ap_wfm/` repo.

`cd` to the `mysite` project, and:

``` bash
$ ln -s ../ap_wfm/ ap_wfm
```
### Install dependencies:

Navigate to the `ap_wfm` directory and install dependencies:

``` bash
$ pip install -r requirements.txt
```
### Database settings:

Edit your `settings.py` database settings. `SQLite` is what we used.

``` py
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3', # Add 'postgresql_psycopg2', 'postgresql', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': 'billy',                      # Or path to database file if using sqlite3.
        'USER': '',                      # Not used with sqlite3.
        'PASSWORD': '',                  # Not used with sqlite3.
        'HOST': '',                      # Set to empty string for localhost. Not used with sqlite3.
        'PORT': '',                      # Set to empty string for default. Not used with sqlite3.
    }
}
```

**Update:** We were not able to get SQLite working; probably best to use another option here.
### Sync the database:

``` bash
$ python manage.py syncdb
```

… and follow the prompts.

**Note:** You may have to update/install Xcode tools:

``` bash
$ xcode-select --install
```
### `urls.py` admin:

Un-comment the relevant lines in the admin. For example:

``` py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^mysite/', include('mysite.ap_wfm.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)
```
### Serve:

``` bash
$ python manage.py runserver
```

… and visit `127.0.0.1:8000/admin`.
### Customize `call_processFeed.py`:

… to suit your local Django project setup. For example, using `mysite`:

``` py
#!/usr/bin/env python
def main():
    import os, sys
    from os import environ
    # Adds parent of wherever file is to sys.path:
    sys.path.append(os.path.join(os.path.abspath(os.path.dirname(__file__)),
                             '..'))
    sys.path.append(os.path.join(os.path.abspath(os.path.dirname(__file__)),
                             '../mysite'))
    environ['DJANGO_SETTINGS_MODULE'] = 'mysite.settings'

    if len(sys.argv) > 1:
        path_to_xml = sys.argv[1]

        from django.core import management
        management.call_command('processFeed', path_to_xml)
    else:
        raise ValueError('Need to supply a path to XML file.')

if __name__ == "__main__": main()
```
### `ap_wfm_settings.py`:

Create an `ap_wfm_settings.py` file in the `ap_wfm/management/commands/` directory.

For your convenience, an example `ap_wfm_settings_example.py` file can be found in the same directory.
### Duplicate an existing AP WebFeeds profile

Login to http://wfm.ap.org

Select "Manage Profiles" from the top right nav

Click "Create New Profile" button in upper right. 

Enter New Profile Name

Select "Copy Existing Profile" dropdown and make a selection.

Click "Next" button in lower righthand.

Click Step 5. "Finish" button in lower righthand.

Skip the Profile Linking, click "Download Agent"
### Download the AP WFM jar:

Visit:

http://wfm.ap.org

**Note:** You may have to install Microsoft Silverlight. Do it.

Sign in using an official log and pass (we're using John's login).

Have John set you up with the Java `jar` goods.

Copy the generated `jar` to you `ap_wfm` app/git repo folder.
### Fire up the `ap_wfm`:

For docs, see:
- [Help index](http://wfm.ap.org/Admin/Content/Help/index.htm)
- [Home > Installation and Startup > Running the Agent on a Remote Server](http://wfm.ap.org/Admin/Content/Help/Running_Agent_on_a_Remote_Server.htm)

``` bash
$ cd ap_wfm/
$ java -jar WebFeedsAgent.jar register agentName=Internet03 userName=foo@foo.com password=xxxxxx
```

**The above `java` command is a ONE-TIME DEAL.**

To get rid of Apple stink, double click on the jar file. You may need to "allow" the java app to run by going here:

![screen shot 2014-06-11 at 3 05 04 pm](https://cloud.githubusercontent.com/assets/218624/3251636/7affce62-f1b4-11e3-985c-1532edf76227.png)
### Post-java-app registration …

Navigate to AP WFM web console and:

![screen shot 2014-06-11 at 3 08 15 pm](https://cloud.githubusercontent.com/assets/218624/3251699/4bc89f7e-f1b5-11e3-9a5c-76720e8e056e.png)

… and then (the Script Location setting on projects.registerguard.com is `projects_root/ap_wfm/call_process_feed.py` :

![screen shot 2014-06-11 at 3 14 45 pm](https://cloud.githubusercontent.com/assets/218624/3251774/59a34f58-f1b6-11e3-9d3d-c20c76756f38.png)
### Start the app:

``` bash
$ java -jar WebFeedsAgent.jar commandLine
```

If you run into problems, check if java app is running via command line:

``` bash
$ ps aux | grep java
```

You'd see two things returned if it's running.

:anger: **WARNING:** DON'T FORGET TO `workon django_root` YOUR VIRTUALENV BEFORE RUNNING SITE!!!!!!!

If you don't see any errors and there's no stories showing in the Django admin, and/or no log file activity, do this:

``` bash
$  ./call_processFeed.py WFA/feeds/US-TopHeadlines-JH/feed_651584_2014-06-11T22-07-24.975Z.xml
```

… and see if it barks. :dog:

_Note that you'll want to link to one of the XML files in your WFA `feeds/` folder; the above is just an example._

**Doing the above is how you detect AP WFM post-processing script errors.**
### Fix any AP WFM errors:

Check the command line output of the java app. If there's problems, fix 'em.

You may need to go back to the AP WFM website console to check/fix settings.

:fire: **PRO TIP:** You can edit the profile on AP's site without having to re-download the `jar` file.
### Re-fire up the development server:

``` bash
$ cd my_site/
$ workon django_root
```

… and navigate to the admin.
